name: Deploy Docs to GitHub Pages

on:
  push:
    branches: [main] # or master, depending on your default branch
    paths:
      - 'docs/**'
      - '.github/workflows/deploy-docs.yml'

  # Allow manual triggering
  workflow_dispatch:

permissions:
  contents: write

jobs:
  deploy:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./docs
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Build website
        run: bun run build

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: docs/build # Adjust this if your build output is in a different location
          branch: gh-pages
          clean: true